-- Couples Narrative Bot — Supabase Migration
-- Run this in the Supabase SQL Editor to set up the database schema.

-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- ═══════════════════════════════════════
-- USERS
-- ═══════════════════════════════════════
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  telegram_id BIGINT UNIQUE NOT NULL,
  username TEXT,
  first_name TEXT,
  pair_id UUID REFERENCES pairs(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ═══════════════════════════════════════
-- PAIRS
-- ═══════════════════════════════════════
CREATE TABLE IF NOT EXISTS pairs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  invite_code TEXT UNIQUE NOT NULL,
  user1_id UUID REFERENCES users(id) ON DELETE SET NULL,
  user2_id UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  paired_at TIMESTAMPTZ
);

-- ═══════════════════════════════════════
-- MESSAGES (encrypted)
-- ═══════════════════════════════════════
CREATE TABLE IF NOT EXISTS messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pair_id UUID NOT NULL REFERENCES pairs(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  encrypted_text TEXT NOT NULL,
  is_personal BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ═══════════════════════════════════════
-- CHAPTERS (generated by LLM)
-- ═══════════════════════════════════════
CREATE TABLE IF NOT EXISTS chapters (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pair_id UUID NOT NULL REFERENCES pairs(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  word_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ═══════════════════════════════════════
-- SAFETY INCIDENTS
-- ═══════════════════════════════════════
CREATE TABLE IF NOT EXISTS safety_incidents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  pair_id UUID REFERENCES pairs(id) ON DELETE SET NULL,
  category TEXT NOT NULL CHECK (category IN ('SUICIDE', 'VIOLENCE', 'SEVERE_DEPRESSION', 'THREAT')),
  confidence NUMERIC(3,2) NOT NULL DEFAULT 0,
  message_preview TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ═══════════════════════════════════════
-- MESSAGE EMBEDDINGS (pgvector)
-- ═══════════════════════════════════════
CREATE TABLE IF NOT EXISTS message_embeddings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id UUID REFERENCES messages(id) ON DELETE CASCADE,
  pair_id UUID NOT NULL REFERENCES pairs(id) ON DELETE CASCADE,
  embedding vector(1536),
  content_preview TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ═══════════════════════════════════════
-- CHAPTER EMBEDDINGS (pgvector)
-- ═══════════════════════════════════════
CREATE TABLE IF NOT EXISTS chapter_embeddings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  chapter_id UUID REFERENCES chapters(id) ON DELETE CASCADE,
  pair_id UUID NOT NULL REFERENCES pairs(id) ON DELETE CASCADE,
  embedding vector(1536),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ═══════════════════════════════════════
-- INDEXES
-- ═══════════════════════════════════════

-- B-tree indexes for common queries
CREATE INDEX IF NOT EXISTS idx_users_telegram_id ON users(telegram_id);
CREATE INDEX IF NOT EXISTS idx_users_pair_id ON users(pair_id);
CREATE INDEX IF NOT EXISTS idx_pairs_invite_code ON pairs(invite_code);
CREATE INDEX IF NOT EXISTS idx_messages_pair_id ON messages(pair_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages(created_at);
CREATE INDEX IF NOT EXISTS idx_chapters_pair_id ON chapters(pair_id);
CREATE INDEX IF NOT EXISTS idx_chapters_created_at ON chapters(created_at);
CREATE INDEX IF NOT EXISTS idx_safety_incidents_user_id ON safety_incidents(user_id);

-- HNSW vector indexes for similarity search
CREATE INDEX IF NOT EXISTS idx_message_embeddings_hnsw
  ON message_embeddings USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 200);

CREATE INDEX IF NOT EXISTS idx_chapter_embeddings_hnsw
  ON chapter_embeddings USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 200);

-- ═══════════════════════════════════════
-- RAG MATCHING FUNCTION
-- ═══════════════════════════════════════
CREATE OR REPLACE FUNCTION match_messages(
  query_embedding vector(1536),
  match_pair_id UUID,
  match_limit INT DEFAULT 5
)
RETURNS TABLE (
  id UUID,
  content_preview TEXT,
  similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    me.id,
    me.content_preview,
    1 - (me.embedding <=> query_embedding) AS similarity
  FROM message_embeddings me
  WHERE me.pair_id = match_pair_id
  ORDER BY me.embedding <=> query_embedding
  LIMIT match_limit;
END;
$$;

-- ═══════════════════════════════════════
-- ROW LEVEL SECURITY (optional, disabled by default for simplicity)
-- ═══════════════════════════════════════
-- ALTER TABLE users ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE pairs ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE chapters ENABLE ROW LEVEL SECURITY;
